//
//  File.swift
//  
//
//  Created by YuAo on 2020/3/16.
//

import Foundation
import ArgumentParser
import URLExpressibleByArgument
import MetalPetalSourceLocator

public struct UmbrellaHeaderGenerator: ParsableCommand {
    
    @Argument(help: "The root directory of the MetalPetal repo.")
    var projectRoot: URL
    
    enum CodingKeys: CodingKey {
        case projectRoot
    }
    
    private let fileManager = FileManager()
    private let explicitlyExcludedHeaderFileNames: Set<String> = [
        "MTIBlendFormulaSupport.h",
        "MTIDefer.h",
        "MTIHasher.h",
        "MTIImageRenderingContext+Internal.h",
        "MTIPrint.h",
        "MetalPetal.h",
    ]
    
    public init() { }
    
    public func run() throws {
        let directoryURL = MetalPetalSourcesRootURL(in: projectRoot)
        let excludedHeaderFiles = try self.excludedHeaderFileNames(in: directoryURL)
        let headerFileNames = self.headerFileNames(in: directoryURL).filter({ !excludedHeaderFiles.contains($0) })
        let content = """
        // MetalPetal Umbrella Header
        // Auto Generated by `swift run main umbrella-header-generator`
        
        \(headerFileNames.reduce("", { result, value in return result + "#import \"\(value)\"\n"}))
        FOUNDATION_EXPORT double MetalPetalVersionNumber;
        FOUNDATION_EXPORT const unsigned char MetalPetalVersionString[];
        
        """
        try! content.write(to: directoryURL.appendingPathComponent("MetalPetal.h"), atomically: true, encoding: .utf8)
    }
    
    private func excludedHeaderFileNames(in directoryURL: URL) throws -> Set<String> {
        var headers = explicitlyExcludedHeaderFileNames
        let modulemap = directoryURL.appendingPathComponent("MetalPetal.modulemap")
        let modulemapContents = try String(contentsOf: modulemap)
        modulemapContents.enumerateLines { (line, stop) in
            if line.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines).hasPrefix("header") {
                let fields = line.split(separator: "\"")
                if fields.count >= 2 {
                    headers.insert(String(fields[1]))
                }
            }
        }
        return headers
    }
    
    private func headerFileNames(in directory: URL) -> [String] {
        var fileNames: [String] = []
        if let contents = try? FileManager.default.contentsOfDirectory(at: directory, includingPropertiesForKeys: nil, options: []) {
            for url in contents.sorted(by: { $0.path < $1.path }) {
                if url.pathExtension == "h" {
                    fileNames.append(url.lastPathComponent)
                } else {
                    let isDirectory = try? url.resourceValues(forKeys: Set([URLResourceKey.isDirectoryKey])).isDirectory
                    if isDirectory ?? false {
                        fileNames.append(contentsOf: headerFileNames(in: url))
                    }
                }
            }
        }
        return fileNames
    }
}
